image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    - scala-lang.scala@0.4.5:hiI5l6gvM8wAiy/xTQl38g==
#    - scalameta.metals@1.9.4:PxYRuGll1yFJGq/sSSA2Fg


tasks:
  - init: "mkdir -p .vscode && echo '{\"metals.sbtScript\": \"/home/gitpod/.local/share/coursier/bin/sbt\"}' > .vscode/settings.json"
  - command: for dir in .cache .config .local; do if test -d /home/gitpod/$dir; then if test -d /workspace/$dir; then rm -rf /home/gitpod/$dir; else mv /home/gitpod/$dir /workspace; fi; fi && if test -d /workspace/$dir; then ln -s /workspace/$dir /home/gitpod/; fi; done

ports:
  - port: 8212
    onOpen: ignore
